# -*- coding: utf-8 -*-
"""predict data of cancer1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hY21MgTQqsBNG4zZ0XxzqD4SiEOuEu_3
"""
# importing data of cancer paitent
from sklearn.datasets import load_breast_cancer
Data = load_breast_cancer()

print(Data.DESCR)

features = Data.data
target = Data.target

print(features.shape)
print(target.shape)

# for trainning a machine we can devide data into train and test 
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(features, target)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
# relu function is used because if value is positive then it remain unchanged and if it is negative then value of
# functionn become zero
model.add(Dense(32, input_dim = 30, activation='relu'))  # hidden layer1
model.add(Dense(64, activation='relu'))     # hidden layer2
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])

model.summary()

model.fit(x_train, y_train, epochs=300)

score = model.evaluate(x_test,y_test)
print(score)    # return loss, acccuracy

prediction = model.predict(x_test)
label1 = []
for pred in prediction:
  if pred>=0.5:
    print('Malignent')
  else:
    print('begin')